# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

variables:
- group: AppVariables

trigger:
- test/azure-extension

pool:
  # vmImage: 'macos-latest' # Cloud
  name: 'MacOS-Agent' # Self-hosted

steps:
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'ac-sample-distribution.p12'
    certPwd: '' # '$(p12-password)'
    keychain: 'temp'
    opensslPkcsArgs: '-legacy'
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'ac-sample-adhoc.mobileprovision'
- task: Xcode@5
  inputs:
    actions: 'clean build'
    configuration: 'Release'
    sdk: 'iphoneos'
    scheme: 'Appcircle'
    packageApp: true
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.ipa'
    TargetFolder: '$(build.artifactStagingDirectory)'
    OverWrite: true
    flattenFolders: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'ac-sample-artifact'
    publishLocation: 'Container'
- task: AppcircleDistribute@0
  inputs:
    accessToken: '$(ac-pat)'
    profileId: 'Test Distribution'
    appPath: '$(Build.ArtifactStagingDirectory)/Appcircle.ipa'
    message: 'Hello from Azure Pipeline'
