name: IPA to EAS

on:
  push:
    branches: [ "test/github-extensions-td-eas-ipa" ]
  pull_request:
    branches: [ "test/github-extensions-td-eas-ipa" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Import .ipa file
      #   env:
      #     IPA_URL: ${{ vars.IPA_URL }}
      #   run: |
      #     git clone $IPA_URL
      #     mv */*.ipa $RUNNER_TEMP
      - name: Import .ipa file
        env:
          APPCIRCLE_IPA_BASE64: ${{ vars.APPCIRCLE_IPA_BASE64 }}
        run: |
          echo -n "$APPCIRCLE_IPA_BASE64" | base64 --decode -o $RUNNER_TEMP/Appcircle.ipa

      - name: Appcircle Enterprise Store
        uses: appcircleio/appcircle-enterprise-store-githubaction@v0.0.1
        env:
          AC_ACCESS_TOKEN: ${{ secrets.AC_ACCESS_TOKEN }}
          AC_ENT_PROFILE_ID: ${{ vars.AC_ENT_PROFILE_ID }}
        with:
          accessToken: $AC_ACCESS_TOKEN
          entProfileId: $AC_ENT_PROFILE_ID
          appPath: $RUNNER_TEMP/Appcircle.ipa
          summary: "This is a summary."
          releaseNotes: "This is a release note."
          publishType: 0
