name: IPA to EAS

on:
  push:
    branches: [ "test/github-extensions-td-eas-ipa" ]
    paths:
      - .github/workflows/ipa-eas.yml
  workflow_dispatch:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import .ipa file
        env:
          IPA_URL: ${{ vars.IPA_URL }}
        run: |
          git clone $IPA_URL
          ls -la
          mv appcircle-sample-ios-ipa $RUNNER_TEMP/ipa
      
      # - name: Import .ipa file
      #   env:
      #     APPCIRCLE_IPA_BASE64: ${{ vars.APPCIRCLE_IPA_BASE64 }}
      #   run: |
      #     echo -n "$APPCIRCLE_IPA_BASE64" | base64 --decode -o $RUNNER_TEMP/Appcircle.ipa

      - name: Appcircle Enterprise Store
        uses: appcircleio/appcircle-enterprise-store-githubaction@feat/SP-201
        with:
          personalAPIToken: ${{ secrets.AC_ACCESS_TOKEN }}
          appPath: ${{ runner.temp }}/${{ vars.APP_PATH }}
          summary: "This is a summary."
          releaseNotes: "This is a release note."
          publishType: ${{ vars.AC_PUBLISH_TYPE }}
