name: IPA to TD

on:
  push:
    branches: [ "test/github-extensions-td-eas-ipa" ]
    paths:
      - .github/workflows/ipa-td.yml
  workflow_dispatch:

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Import .ipa file
      #   env:
      #     IPA_URL: ${{ vars.IPA_URL }}
      #   run: |
      #     git clone $IPA_URL
      #     mv */*.ipa $RUNNER_TEMP
      - name: Import .ipa file
        env:
          APPCIRCLE_IPA_BASE64: ${{ vars.APPCIRCLE_IPA_BASE64 }}
        run: |
          echo -n "$APPCIRCLE_IPA_BASE64" | base64 --decode -o $RUNNER_TEMP/Appcircle.ipa

      - name: Find Artifacts
        run: |
          find "${RUNNER_TEMP}" -type f \( -name "*.apk" -o -name "*.aab" \)
          ls -l "${RUNNER_TEMP}"

      - name: Appcircle Testing Distribution
        uses: appcircleio/appcircle-testing-distribution-githubaction@feat/SP-201
        with:
          personalAPIToken: ${{ secrets.AC_ACCESS_TOKEN }}
          profileName: ${{ vars.AC_PROFILE_NAME }}
          createProfileIfNotExists: ${{ vars.AC_CREATE_PROFILE_IF_NOT_EXISTS }}
          appPath: $RUNNER_TEMP/Appcircle.ipa
          message: "Hello from Github to TD"
