name: iOS build workflow

on:
  push:
    branches: [ "test/github-extensions-td-eas" ]
  pull_request:
    branches: [ "test/github-extensions-td-eas" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      
      - name: Decode the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        run: |
          # create variables
          mkdir -p $GITHUB_WORKSPACE/certificates
          CERTIFICATE_PATH=$GITHUB_WORKSPACE/certificates/ac-sample-distribution.p12
          PP_PATH=$GITHUB_WORKSPACE/certificates/ac-sample-adhoc.mobileprovision

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

      - name: Debug Env.
        run: |
          echo "$RUNNER_TEMP"
          ls $RUNNER_TEMP
          echo "$GITHUB_WORKSPACE"
          ls $GITHUB_WORKSPACE
          echo "Certificates"
          ls $GITHUB_WORKSPACE/certificates
          
      - name: Build
        env:
          AC_PP_UUID: ${{ vars.PROVISIONING_PROFILE }}
        run: |
          echo $AC_PP_UUID
          bundle exec fastlane ios build_signed
      
